# Generated by Django 5.2.4 on 2025-08-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participant',
        ),
        migrations.AddField(
            model_name='participant',
            name='events',
            field=models.ManyToManyField(related_name='particepant', to='event.participant'),
        ),
    ]
