# Generated by Django 5.2.4 on 2025-08-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_participant_participant_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='events',
            field=models.ManyToManyField(related_name='particepant', to='event.event'),
        ),
    ]
