# Generated by Django 5.2.4 on 2025-08-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='events_asset/default.jpg', null=True, upload_to='events_asset'),
        ),
    ]
